module.exports = {
  Alerts: require("./features/global/Alerts"),
  BatteryAbsoluteTime: require("./features/game/BatteryAbsoluteTime"),
  BatteryPercent: require("./features/game/BatteryPercent"),
  ChangeBodyColor: require("./features/global/ChangeBodyColor"),
  CharacterCounter: require("./features/threads/CharacterCounter"),
  EasyCite: require("./features/global/EasyCite"),
  ExpandBlockedPosts: require("./features/threads/ExpandBlockedPosts"),
  HFToolBar: require("./features/global/HFToolBar"),
  HideBlockedPosts: require("./features/threads/HideBlockedPosts"),
  HideClosedThreads: require("./features/forumdisplay/HideClosedThreads"),
  HideImages: require("./features/global/HideImages"),
  HidePostbitAttributes: require("./features/threads/HidePostbitAttributes"),
  MedalOfHonorTracker: require("./features/game/MedalOfHonorTracker"),
  PMFromPost: require("./features/threads/PMFromPost"),
  PostsOnThread: require("./features/threads/PostsOnThread"),
  RepCharts: require("./features/reputation/RepCharts"),
  SearchYourThreads: require("./features/forumdisplay/SearchYourThreads"),
  ShortcutLeaderboard: require("./features/game/ShortcutLeaderboard"),
  ShortcutLogs: require("./features/game/ShortcutLogs"),
  SmartQuote: require("./features/threads/SmartQuote"),
  ShowPostNumbers: require("./features/threads/ShowPostNumbers"),
  TrackingLinks: require("./features/pms/TrackingLinks")
};
